# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np
from numpy import linalg

In [ ]:
m1 = np.arange(1, 10).reshape(3, 3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# прибавление единичной матрицы 3х3
m2 = m1 + np.eye(3)
m2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
# умножение на вектор
m3 = m2 * np.array([1, 2, 3])
m3

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [ ]:
# транспонирование
m4 = np.transpose(m2)
m4

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
# обратная матрица
m5 = np.linalg.inv(m2)
m5

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
# проверка, что m2 @ m5 даст единичную матрицу
m2 @ m5

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
# вычисление собственных значений
np.linalg.eigvals(m)

array([1., 4.])

In [ ]:
# собственный вектор
# первый элемент в результате - собственные значения, остальные - собственные векторы (тут 2)
np.linalg.eig(m)

EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))

In [ ]:
# приведем векторы к более красивому виду
res = np.linalg.eig(m)[1]
res

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [ ]:
res2 = np.transpose(res)
res2

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

In [ ]:
res2[0] / 0.4472136

array([-1.99999998,  0.99999999])

In [ ]:
res2[1] / -0.70710678

array([1., 1.])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
m = np.array([[1, 1], [1, 2]])
m

array([[1, 1],
       [1, 2]])

In [ ]:
det = np.linalg.det(m)
det

np.float64(1.0)

In [ ]:
import numpy as np

def find_matrix_with_det_1():
    for i in range(2, 100):
        for _ in range(100000):
            matrix = np.random.randint(1, 11, size=(i,i))
            det = np.linalg.det(matrix)
            # Сравнение с плавающей точкой через допуск 1e-8 = 0.00000001
            # Избегаем ошибок округления: det может быть 0.9999999999, а не 1.0
            if abs(det - 1.0) < 1e-8:
                print(matrix)
                return

find_matrix_with_det_1()

[[4 5]
 [7 9]]
